import swaggerJsdoc from "swagger-jsdoc";

export const swaggerSpec = swaggerJsdoc({
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Shop Liên Quân API - OpenAPI Spec",
      version: "1.0.0",
      description: "Tài liệu OpenAPI 3.0 / JSON API đầy đủ cho hệ thống website bán tài khoản game Liên Quân Mobile.",
      contact: {
        name: "API Support",
        email: "support@shoplienquan.com",
      },
    },
    servers: [
      {
        url: "http://localhost:3000",
        description: "Local Development Server",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Nhập JWT Access Token dạng: Bearer <token>",
        },
      },
      schemas: {
        User: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            username: { type: "string", example: "user123" },
            level: { type: "integer", example: 0, description: "0: Member, 1: CTV, 99: Admin" },
            money: { type: "integer", example: 500000, description: "Số dư tài khoản (VNĐ)" },
            tong_nap: { type: "integer", example: 1000000, description: "Tổng số tiền đã nạp (VNĐ)" },
            banned: { type: "boolean", example: false },
            ip: { type: "string", example: "127.0.0.1" },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        Category: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            name: { type: "string", example: "Acc Liên Quân" },
            noidung: { type: "string", example: "Danh mục tài khoản Liên Quân Mobile" },
            type: { type: "string", example: "lienquan" },
            status: { type: "integer", example: 1, description: "1: Hoạt động, 0: Ẩn" },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        AccountType: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            danhmuc_id: { type: "integer", example: 1 },
            name: { type: "string", example: "Nick Rank Cao" },
            img: { type: "string", example: "https://domain.com/images/thumb.jpg" },
            noidung: { type: "string", example: "Chi tiết loại tài khoản rank cao" },
            camket: { type: "string", example: "Cam kết đúng mô tả, bảo hành 100%" },
            view: { type: "integer", example: 150 },
            buy: { type: "integer", example: 25 },
            status: { type: "integer", example: 1 },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        GameAccount: {
          type: "object",
          properties: {
            id: { type: "integer", example: 101 },
            loai_id: { type: "integer", example: 1 },
            buyer_id: { type: "integer", nullable: true, example: 5 },
            seller_id: { type: "integer", nullable: true, example: 2 },
            thong_tin: { type: "string", example: "Acc Rank Cao Thủ - 80 Tướng" },
            list_thong_tin: { type: "string", example: "Rank: Cao Thủ | Tướng: 80 | Trang phục: 50" },
            img: { type: "string", example: "https://domain.com/uploads/acc101.jpg" },
            list_img: { type: "string", example: "[\"img1.jpg\", \"img2.jpg\"]" },
            login: { type: "string", description: "Thông tin tài khoản/mật khẩu đăng nhập (chỉ trả về khi xem đơn hàng)", example: "user_game|pass_game" },
            gia: { type: "integer", example: 250000 },
            sale_price: { type: "integer", nullable: true, example: 200000, description: "Giá sale cấu hình trực tiếp cho account; khác Flash Sale có thời gian" },
            ck: { type: "integer", example: 0, description: "Phần trăm chiết khấu cho CTV" },
            status: { type: "integer", example: 0, description: "0: Đang bán, 1: Đã bán, 2: Đã ẩn" },
            ngaymua: { type: "string", format: "date-time", nullable: true },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        Order: {
          type: "object",
          properties: {
            id: { type: "integer", example: 50 },
            user_id: { type: "integer", example: 5 },
            acc_id: { type: "integer", example: 101 },
            original_price: { type: "integer", example: 250000 },
            sale_id: { type: "integer", nullable: true, example: null },
            sale_price: { type: "integer", nullable: true, example: null },
            discount_id: { type: "integer", nullable: true, example: 2 },
            discount_amount: { type: "integer", example: 25000 },
            final_price: { type: "integer", example: 225000 },
            status: { type: "integer", example: 1, description: "1: Thành công" },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        Transaction: {
          type: "object",
          properties: {
            id: { type: "integer", example: 88 },
            user_id: { type: "integer", example: 5 },
            type: {
              type: "string",
              enum: ["deposit", "buy_acc", "refund", "admin_add", "admin_sub", "ctv_earn"],
              example: "buy_acc"
            },
            amount: { type: "integer", example: -225000 },
            balance_before: { type: "integer", example: 500000 },
            balance_after: { type: "integer", example: 275000 },
            reference_id: { type: "integer", nullable: true, example: 50 },
            description: { type: "string", example: "Thanh toán mua tài khoản #101" },
            created_at: { type: "string", format: "date-time" },
          },
        },
        Discount: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            magiamgia: { type: "string", example: "WELCOME10" },
            theo: { type: "string", enum: ["phantram", "tienmat"], example: "phantram" },
            giamgia: { type: "integer", example: 10 },
            soluong: { type: "integer", example: 100 },
            status: { type: "integer", example: 1 },
            batdau: { type: "string", format: "date-time", nullable: true },
            ketthuc: { type: "string", format: "date-time", nullable: true },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        Bank: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            name: { type: "string", example: "MBBank" },
            bank_id: { type: "string", example: "MB" },
            account_no: { type: "string", example: "0987654321" },
            account_name: { type: "string", example: "NGUYEN VAN A" },
            logo: { type: "string", nullable: true },
            status: { type: "integer", example: 1 },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        Setting: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            ten_web: { type: "string", example: "Shop Liên Quân Uy Tín" },
            logo: { type: "string", nullable: true },
            banner: { type: "string", nullable: true },
            thongbao: { type: "string", nullable: true },
            sepay_configured: { type: "boolean", description: "Trạng thái tích hợp SePay; chỉ có trong response Admin" },
            sepay_secret_saved: { type: "boolean", description: "Đã lưu khóa SePay trong Admin; không trả nội dung khóa" },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
        },
        ApiResponse: {
          type: "object",
          properties: {
            status: { type: "string", example: "success" },
            message: { type: "string", example: "Thao tác thành công" },
            data: { type: "object" },
          },
        },
        ErrorResponse: {
          type: "object",
          properties: {
            status: { type: "string", example: "error" },
            message: { type: "string", example: "Thông tin không hợp lệ hoặc không tìm thấy dữ liệu" },
          },
        },
      },
    },
  },
  apis: ["./src/routes/*.js"],
});
